### ISSUE TITLE
It's currently putting <strong> around the addresses

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/hawkesbury#1]
Eek!

**Comment by mlandauer** [comment]
It's not the migration to Morph that's the problem. Looking through the data it looks like it broke about twelve months ago

**Comment by henare** [comment]
I've disabled autorun on this scraper until this is fixed.

**Comment by henare** [comment]
Fixed in fdf7ddfa257b76b92cc8543e3d8e467bc5a821d6
